/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaGUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Jespi_000
 */
public class VentanaPrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public VentanaPrincipalGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelBienvenido = new javax.swing.JLabel();
        LabelOperacion = new javax.swing.JLabel();
        ComboBoxOperacion = new javax.swing.JComboBox();
        BarraDeMenu = new javax.swing.JMenuBar();
        MenuAyuda = new javax.swing.JMenu();
        MenuCreditos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(255, 153, 51));
        setForeground(new java.awt.Color(255, 153, 51));

        LabelBienvenido.setText("¡Bienvenido!");

        LabelOperacion.setText("Seleccione la operación de desea realizar:");

        ComboBoxOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccione la operación--", "Sumar", "Restar", "Multiplicar", "Dividir", "Elevar", "Raíz Cuadrada", "Convertir a Octal", "Convertir a Binario", "Convertir a Hexadecimal" }));
        ComboBoxOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOperacionActionPerformed(evt);
            }
        });

        MenuAyuda.setText("Ayuda");
        MenuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAyudaMouseClicked(evt);
            }
        });
        BarraDeMenu.add(MenuAyuda);

        MenuCreditos.setText("Créditos");
        MenuCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCreditosMouseClicked(evt);
            }
        });
        MenuCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCreditosActionPerformed(evt);
            }
        });
        BarraDeMenu.add(MenuCreditos);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelOperacion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(LabelBienvenido))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(ComboBoxOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBienvenido)
                .addGap(35, 35, 35)
                .addComponent(LabelOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOperacionActionPerformed
        if (!(ComboBoxOperacion.getSelectedItem().toString().equals("--Seleccione la operación--"))){
            String operacion = ComboBoxOperacion.getSelectedItem().toString();
            this.setVisible(false);
            switch (operacion){
                
                //OPERACIONES
                
                case "Sumar":
                    OperacionGUI OpSumar = new OperacionGUI("Suma","Sumar Números");
                    OpSumar.setVisible(true);
                    break;
                case "Restar":
                    OperacionGUI OpRestar = new OperacionGUI("Resta","Restar Números");
                    OpRestar.setVisible(true);
                    break;
                case "Multiplicar":
                    OperacionGUI OpMultiplicar = new OperacionGUI("Multiplicacion","Multiplicar Números");
                    OpMultiplicar.setVisible(true);
                    break;
                case "Dividir":
                    OperacionGUI OpDividir = new OperacionGUI("Division","Dividir Números");
                    OpDividir.setVisible(true);
                    break;
                case "Elevar":
                    OperacionGUI OpElevar = new OperacionGUI("Potencia","Elevar Números");
                    OpElevar.setVisible(true);
                    break;
                case "Raíz Cuadrada":
                    OperacionGUI OpRadicar = new OperacionGUI("Radicacion","Raíz cuadrada de un número");
                    OpRadicar.setVisible(true);
                    break;
                    
                //CONVERSIONES
                    
                case "Convertir a Octal":
                    ConversionGUI COctal = new ConversionGUI("Octal","Convertir Decimal a Octal");
                    COctal.setVisible(true);
                    break;
                case "Convertir a Binario":
                    ConversionGUI CBinario = new ConversionGUI("Binario","Convertir Decimal a Binario");
                    CBinario.setVisible(true);
                    break;
                case "Convertir a Hexadecimal":
                    ConversionGUI CHexadecimal = new ConversionGUI("Hexadecimal","Convertir Decimal a Hexadecimal");
                    CHexadecimal.setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_ComboBoxOperacionActionPerformed

    private void MenuCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCreditosActionPerformed
        
    }//GEN-LAST:event_MenuCreditosActionPerformed

    private void MenuCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCreditosMouseClicked
        JOptionPane.showMessageDialog(new JFrame(), "El presente proyecto fue desarollado para el curso de Diseño de Software del I Semestre, 2015, por los estudiantes:\n\n - Josué Espinoza Castro\n - Luis Mauricio Gamboa Cubero\n - Andrés Mauricio Pacheco Quesada", "Créditos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuCreditosMouseClicked

    private void MenuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAyudaMouseClicked
        JOptionPane.showMessageDialog(new JFrame(), "¡Bienvenido!\n\nPara ejecutar: seleccione la operación deseada.\nLuego, modifique los parámetros de la operación y obtenga el resultado.", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JComboBox ComboBoxOperacion;
    private javax.swing.JLabel LabelBienvenido;
    private javax.swing.JLabel LabelOperacion;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuCreditos;
    // End of variables declaration//GEN-END:variables
}
